### ISSUE TITLE
"A previous session terminated unexpectedly. Disabling extension ConstVisualizer 1.20 might help"

### ISSUE THREAD

**Issue by MagicAndre1981** [mrlacey/ConstVisualizer#13]
I get this message in VS2022 17.2 Preview 4:

![const_vis_2022_17_2_p4](https://user-images.githubusercontent.com/8274816/164394079-e567c931-b743-42f1-b1c4-8de4c0c2a1ab.png)

Have you seen something like this before?

**Comment by mrlacey** [comment]
Hmm. I've just gotten this too and I wasn't even aware that a session had ended unexpectedly.
I'm not sure what the issue is here. But will have a look into possible ideas.

**Comment by mrlacey** [comment]
![image](https://user-images.githubusercontent.com/189547/165096855-c2d329d0-8692-46be-ac53-ed0faa99cead.png)

via https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?view=vs-2022#extension-crash-and-unresponsiveness-notifications

That's not helpful. Is it? :(
"There was a crash and you were there so we're going to blame you" 😞

**Comment by MagicAndre1981** [comment]
> Hmm. I've just gotten this too and I wasn't even aware that a session had ended unexpectedly. 

I also didn't notice any crash. That is why I was so confused

**Comment by MagicAndre1981** [comment]
ok, I got a warning about missing drivespace and saw a lot of devenv dmp files. 1 shows me this:


```
EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007fff2d83e690 (ConstVisualizer!ConstVisualizer.ConstFinder.SafeGetActiveDocument+0x0000000000000030)
   ExceptionCode: 00000000
  ExceptionFlags: 00000000
NumberParameters: 0

PROCESS_NAME:  devenv.exe
```

offset is very large, so it may not be in this method but a method that is called from SafeGetActiveDocument.

Maybe this helps you.

**Comment by mrlacey** [comment]
I've just released v1.21 which includes a small change that I hope will make an improvement to address at least some of the times this happens.

I think it's going to need a full rewrite and a new approach to providing the functionality to address this properly though :(

progress, hopefully, continues

**Comment by MagicAndre1981** [comment]
> I've just released v1.21 which includes a small change that I hope will make an improvement to address at least some of the times this happens.

I still get it with 1.21 and I think I always get it while opening csproj files to edit them directly :

![const_viz_erro_121](https://user-images.githubusercontent.com/8274816/186008006-51114f59-9552-4b5d-a41f-d83f4543fcc7.png)

<HTML><HEAD> </HEAD><BODY><DIV class="wrapper"><DIV id="ng-view"><DIV class="grid-container"><DIV class="row"><DIV style="margin-top: 60px;"><DIV style="margin-top: 60px;"><DIV class="analysisDetailsSection"><DIV id="analysisDetailsGroup"><DIV class="normalText group" id="group"><DIV class="mt20" id="B1" style="display: block;" data-debug-rule="CrashHangAnalysis" data-debug-details="parent"><DIV class="normalText group" id="B1group"><DIV class="mt20 dump" id="B1C1" style="display: block;" data-debug-rule="CrashHangAnalysis" data-debug-dump="devenv.exe.7996.dmp" data-debug-details="dump"><DIV class="normalText group" id="B1C1group"><DIV class="mt20 custom" id="FaultingThreadB1C1" data-debug-rule="CrashHangAnalysis" data-debug-dump="devenv.exe.7996.dmp" data-debug-details="custom"><DIV class="normalText group" id="FaultingThreadB1C1group"><DIV class="mt10 ml15 normalText"><B>.NET Call Stack</B><BR><BR><TABLE class="myCustomText" border="0" cellspacing="0" cellpadding="0"><TBODY><TR><TH></TH></TR><TR><TD nowrap=""><FONT color="darkblue">[[HelperMethodFrame] </FONT>(System.Diagnostics.Debugger.BreakInternal)] System.Diagnostics.Debugger.BreakInternal()</TD></TR><TR><TD nowrap=""><FONT color="darkblue">mscorlib_ni!System.Diagnostics.Debugger.Break</FONT>()+5e</TD></TR><TR><TD nowrap=""><FONT color="darkblue">ConstVisualizer.ConstFinder.SafeGetActiveDocument</FONT>(EnvDTE.DTE)+5e</TD></TR><TR><TD nowrap="">[[HelperMethodFrame]]</TD></TR><TR><TD nowrap=""><FONT color="darkblue">Microsoft_VisualStudio_Interop_ni!DomainNeutralILStubClass.IL_STUB_CLRtoCOM</FONT>()+12b</TD></TR><TR><TD nowrap=""><FONT color="darkblue">[[InlinedCallFrame] </FONT>(EnvDTE.DTE.get_ActiveDocument)] EnvDTE.DTE.get_ActiveDocument()</TD></TR><TR><TD nowrap=""><FONT color="darkblue">ConstVisualizer.ConstFinder.SafeGetActiveDocument</FONT>(EnvDTE.DTE)+30</TD></TR><TR><TD nowrap=""><FONT color="darkblue">ConstVisualizer.ConstFinder+<reloadconstsasync>d__10.MoveNext</reloadconstsasync></FONT>()+1dd</TD></TR><TR><TD nowrap=""><FONT color="darkblue">System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[ConstVisualizer.ConstFinder+<reloadconstsasync>d__10, ConstVisualizer]]</reloadconstsasync></FONT>(<reloadconstsasync>d__10 ByRef)+80</reloadconstsasync></TD></TR><TR><TD nowrap=""><FONT color="darkblue">ConstVisualizer.ConstFinder.ReloadConstsAsync</FONT>()+45</TD></TR><TR><TD nowrap=""><FONT color="darkblue">ConstVisualizer.MyRunningDocTableEvents+&lt;&gt;c+&lt;<onbeforedocumentwindowshow>b__8_0&gt;d.MoveNext</onbeforedocumentwindowshow></FONT>()+27</TD></TR><TR><TD nowrap=""><FONT color="darkblue">System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[ConstVisualizer.MyRunningDocTableEvents+&lt;&gt;c+&lt;<onbeforedocumentwindowshow>b__8_0&gt;d, ConstVisualizer]]</onbeforedocumentwindowshow></FONT>(&lt;<onbeforedocumentwindowshow>b__8_0&gt;d ByRef)+80</onbeforedocumentwindowshow></TD></TR><TR><TD nowrap=""><FONT color="darkblue">ConstVisualizer.MyRunningDocTableEvents+&lt;&gt;c.<onbeforedocumentwindowshow>b__8_0</onbeforedocumentwindowshow></FONT>()+49</TD></TR><TR><TD nowrap=""><FONT color="darkblue">Microsoft_VisualStudio_Threading_ni!Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[[Microsoft.VisualStudio.Threading.EmptyStruct, Microsoft.VisualStudio.Threading]]</FONT>(System.Func`1<system.threading.tasks.task>, Microsoft.VisualStudio.Threading.JoinableTask)+49</system.threading.tasks.task></TD></TR><TR><TD nowrap=""><FONT color="darkblue">Microsoft_VisualStudio_Threading_ni!Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync</FONT>(System.Func`1<system.threading.tasks.task>, Boolean, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions, System.Delegate)+7b</system.threading.tasks.task></TD></TR><TR><TD nowrap=""><FONT color="darkblue">ConstVisualizer.MyRunningDocTableEvents.OnBeforeDocumentWindowShow</FONT>(UInt32, Int32, Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame)+b1</TD></TR><TR><TD nowrap=""><FONT color="darkblue">Microsoft_VisualStudio_Interop_ni!DomainNeutralILStubClass.IL_STUB_COMtoCLR</FONT>(Int32, Int32, IntPtr)+49</TD></TR><TR><TD nowrap="">[[ComMethodFrame]]</TD></TR><TR><TD nowrap=""><FONT color="darkblue">Microsoft_Internal_VisualStudio_Interop_ni!DomainNeutralILStubClass.IL_STUB_CLRtoCOM</FONT>(UInt32, Int32, Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame)+f1</TD></TR><TR><TD nowrap=""><FONT color="darkblue">[[InlinedCallFrame] </FONT>(Microsoft.Internal.VisualStudio.Shell.Interop.IVsRunningDocumentTablePrivate.NotifyOnBeforeShow)] Microsoft.Internal.VisualStudio.Shell.Interop.IVsRunningDocumentTablePrivate.NotifyOnBeforeShow(UInt32, Int32, Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame)</TD></TR><TR><TD nowrap=""><FONT color="darkblue">Microsoft_VisualStudio_Platform_WindowManagement_ni!Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.NotifyFrameShowing</FONT>(UInt32, Boolean)+b9</TD></TR><TR><TD nowrap=""><FONT color="darkblue">Microsoft_VisualStudio_Platform_WindowManagement_ni!Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.NotifyFrameShowing</FONT>()+3b</TD></TR><TR><TD nowrap=""><FONT color="darkblue">Microsoft_VisualStudio_Platform_WindowManagement_ni!Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.OnContentShowing</FONT>(Microsoft.VisualStudio.PlatformUI.Shell.View)+6d</TD></TR><TR><TD nowrap="">[[DebuggerU2MCatchHandlerFrame]]</TD></TR><TR><TD nowrap=""><FONT color="darkblue">[[HelperMethodFrame_PROTECTOBJ] </FONT>(System.RuntimeMethodHandle.InvokeMethod)] System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)</TD></TR><TR><TD nowrap=""><FONT color="darkblue">mscorlib_ni!System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal</FONT>(System.Object, System.Object[], System.Object[])+d8</TD></TR><TR><TD nowrap=""><FONT color="darkblue">mscorlib_ni!System.Delegate.DynamicInvokeImpl</FONT>(System.Object[])+a0</TD></TR><TR><TD nowrap=""><FONT color="darkblue">PresentationCore_ni!System.Windows.RoutedEventArgs.InvokeEventHandler</FONT>(System.Delegate, System.Object)+d0</TD></TR><TR><TD nowrap=""><FONT color="darkblue">PresentationCore_ni!System.Windows.RoutedEventArgs.InvokeHandler</FONT>(System.Delegate, System.Object)+2f</TD></TR><TR><TD nowrap=""><FONT color="darkblue">PresentationCore_ni!System.Windows.RoutedEventHandlerInfo.InvokeHandler</FONT>(System.Object, System.Windows.RoutedEventArgs)+46</TD></TR><TR><TD nowrap=""><FONT color="darkblue">PresentationCore_ni!System.Windows.EventRoute.InvokeHandlersImpl</FONT>(System.Object, System.Windows.RoutedEventArgs, Boolean)+f4</TD></TR><TR><TD nowrap=""><FONT color="darkblue">PresentationCore_ni!System.Windows.UIElement.RaiseEventImpl</FONT>(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)+88</TD></TR><TR><TD nowrap=""><FONT color="darkblue">Microsoft_VisualStudio_Shell_ViewManager_ni!Microsoft.VisualStudio.PlatformUI.Shell.Controls.ViewPresenter.<asyncraiseevent>b__12_0</asyncraiseevent></FONT>(System.Object)+60</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!System.Windows.Threading.ExceptionWrapper.InternalRealCall</FONT>(System.Delegate, System.Object, Int32)+68</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!System.Windows.Threading.ExceptionWrapper.TryCatchWhen</FONT>(System.Object, System.Delegate, System.Object, Int32, System.Delegate)+36</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!System.Windows.Threading.DispatcherOperation.InvokeImpl</FONT>()+10c</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!MS.Internal.CulturePreservingExecutionContext.CallbackWrapper</FONT>(System.Object)+4d</TD></TR><TR><TD nowrap=""><FONT color="darkblue">mscorlib_ni!System.Threading.ExecutionContext.RunInternal</FONT>(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+108</TD></TR><TR><TD nowrap=""><FONT color="darkblue">mscorlib_ni!System.Threading.ExecutionContext.Run</FONT>(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+15</TD></TR><TR><TD nowrap=""><FONT color="darkblue">mscorlib_ni!System.Threading.ExecutionContext.Run</FONT>(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+55</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!MS.Internal.CulturePreservingExecutionContext.Run</FONT>(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)+b1</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!System.Windows.Threading.DispatcherOperation.Invoke</FONT>()+62</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!System.Windows.Threading.Dispatcher.ProcessQueue</FONT>()+1fd</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!System.Windows.Threading.Dispatcher.WndProcHook</FONT>(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)+6f</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!MS.Win32.HwndWrapper.WndProc</FONT>(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)+c4</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!MS.Win32.HwndSubclass.DispatcherCallbackOperation</FONT>(System.Object)+84</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!System.Windows.Threading.ExceptionWrapper.InternalRealCall</FONT>(System.Delegate, System.Object, Int32)+68</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!System.Windows.Threading.ExceptionWrapper.TryCatchWhen</FONT>(System.Object, System.Delegate, System.Object, Int32, System.Delegate)+36</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!System.Windows.Threading.Dispatcher.LegacyInvokeImpl</FONT>(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)+172</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!MS.Win32.HwndSubclass.SubclassWndProc</FONT>(IntPtr, Int32, IntPtr, IntPtr)+152</TD></TR><TR><TD nowrap=""><FONT color="darkblue">WindowsBase_ni!DomainNeutralILStubClass.IL_STUB_ReversePInvoke</FONT>(Int64, Int32, Int64, Int64)+52</TD></TR></TBODY></TABLE></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></BODY></HTML>

**Comment by MagicAndre1981** [comment]
the callstack is wired as Debugger.Break() is called so no real crash. Maybe @madskristensen has any idea what goes wrong here.

**Comment by madskristensen** [comment]
This looks weird to me. I've never seen some of these symbols before. Like 'HelperMethodFrame' and `ConstVisualizer`. @aarnott any clue?

**Comment by MagicAndre1981** [comment]
> This looks weird to me. I've never seen some of these symbols before. Like `HelperMethodFrame` and `ConstVisualizer`. 

ConstVisualizer is the name of this extension. I added you as the VS extension guru to give us any ideas why this happens since VS2022 17.2 Preview 4

**Comment by madskristensen** [comment]
Doh!! It looks like it's the `Debugger.Break()` statement causing the issue. You're not calling that, are you?

**Comment by MagicAndre1981** [comment]
also **d'oh** 🤦  , @mrlacey [silently added this break](https://github.com/mrlacey/ConstVisualizer/commit/e475b7e23d7ddfdea1a6f83adae44bee4aabd0ad), but the issues happened before. real issue is why EnvDTE.DTE.get_ActiveDocument() fails and I think this triggers the **yellow bar** on each start.

**Comment by madskristensen** [comment]
Are you using the 2019 VSSDK and the exception happens when using the DTE in 2022? The DTE isn't compatible across the 32-bit (2019) and 64-bit (2022) boundary.

**Comment by MagicAndre1981** [comment]
> Nope, it's VS2022 only. Using the 17.2 version of the SDK

I've updated the SDK to 17.3, debugged it in exp instance and saw no warning. I also started/closed the exp instance several times, edited a csproj and I haven't seen any warning.

Maybe also try 17.3 SDKs and [require 17.3 in vsixmanifest](https://github.com/mrlacey/ConstVisualizer/blob/f8f2b4c1139399d7dfbb30ead80d0c3db49ba1d3/src/ConstVisualizer/source.extension.vsixmanifest#L12).

Or maybe this detection is disabled in exp instance. Who knows 🤷‍♂️

**Comment by mrlacey** [comment]
v1.22 uses version 17.0 of the VSSDK and I've been testing with this version over the last couple of days without seeing the error prompt.
Hopefully this addresses the issue........

**Comment by MagicAndre1981** [comment]
> v1.22 uses version **17.0 of the VSSDK** and I've been testing with this version over the last couple of days without seeing the error prompt. **Hopefully this addresses the issue**........

it did for me. I haven't see the message again and got no new devenv.exe.dmp files. So why does the downgrade to 17.0 SDK fix the issue? @madskristensen

**Comment by madskristensen** [comment]
If you're using v17.3 of the SDK, then you should target v17.3 of Visual Studio or higher. You cannot target 17.0 due to possible API changes. You wouldn't have seen any issue when you have 17.3 installed and using VSSDK 17.3, but people that are still on 17.2 or lower could have

**Comment by MagicAndre1981** [comment]
I use VS17.3 and had the issue when the extension used the 17.2 VSSDK. Now with VSSDK 17.0 everything is fine when using the extension under 17.4 P1 and 17.3. This is confusing as it started with 17.2 Preview 4. And 17.2 is LTS version of VS2022, so what should extension authors do? Use VSSDK 17.0 all time and never update even if they only support >=17.2?  @madskristensen

**Comment by mrlacey** [comment]
Closing this as it no longer seems to be happening.
Assuming it was related to a version mis-match.

**Comment by MagicAndre1981** [comment]
I also no longer see it with your latest version which uses 17.0 SDK
